import = ["~/.config/alacritty/themes/themes/challenger_deep.toml"]

[window]
opacity = 0.8

[keyboard]
# Example
bindings = [
    { key = "Return", mods = "Command", action = "ToggleSimpleFullscreen" }
]

[font]
normal = { family = "CaskaydiaCove Nerd Font", style = "Regular"}
size = 15.0